test
test1
test2
test3
test4
test5

Fatal error: %s
Stack trace:
#0 %s(%d): B->test()
#1 {main}
  thrown in %sbug42937.php on line 21