
Fatal error: %s
Stack trace:
#0 %s(%d): {closure}(Object(class@anonymous))
#1 {main}
  thrown in %s on line %d