
Fatal error: %s
Stack trace:
#0 %s(%d): C->f()
#1 {main}
  thrown in %s on line 5