
Fatal error: %s
Stack trace:
#0 [internal function]: autoload('SyntaxError')
#1 %s(%d): spl_autoload_call('SyntaxError')
#2 %s(%d): testGenerator()
#3 {main}
  thrown in %s on line %d